name: Auto back merge to develop

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
      - name: Merge master back to develop
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: "develop"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
