# This is a basic workflow to help you get started with Actions

name: Auto back merge to develop

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@develop
      - name: Merge master back to develop
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: "develop"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
